# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Network_progress_pop' do
  pod 'MBProgressHUD'

  target 'Network_progress_popTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Network_progress_popUITests' do
    inherit! :search_paths
    # Pods for testing


  end

end
